-- Áreas Marketing y Comunicación (migración noticias_marketing_comunicacion), verificadas el 2026-10-02 con el
-- mismo criterio que el resto: web con notas de las últimas semanas, X o Bluesky con posts propios del último mes.
insert into public.noticias_medios (owner_id, medio, pais, idioma, sitio, rss, x, bluesky, temas, tipo, descripcion)
select (select owner_id from public.trabajadores order by id limit 1), m.* from (values
('Adweek', 'US', 'en', 'https://www.adweek.com', 'https://www.adweek.com/feed/', 'Adweek', null, array['marketing'], 'medio', null),
('Marketing Dive', 'US', 'en', 'https://www.marketingdive.com', 'https://www.marketingdive.com/feeds/news/', 'MarketingDive', null, array['marketing'], 'medio', null),
('Digiday', 'US', 'en', 'https://digiday.com', 'https://digiday.com/feed/', 'Digiday', null, array['marketing'], 'medio', null),
('The Drum', 'GB', 'en', 'https://www.thedrum.com', null, 'TheDrum', null, array['marketing'], 'medio', null),
('Campaign', 'GB', 'en', 'https://www.campaignlive.co.uk', null, 'campaignmag', null, array['marketing'], 'medio', null),
('Marketing Week', 'GB', 'en', 'https://www.marketingweek.com', 'https://www.marketingweek.com/feed/', null, null, array['marketing'], 'medio', null),
('Social Media Today', 'US', 'en', 'https://www.socialmediatoday.com', 'https://www.socialmediatoday.com/feeds/news/', null, null, array['marketing'], 'medio', null),
('Search Engine Land', 'US', 'en', 'https://searchengineland.com', null, 'sengineland', null, array['marketing'], 'medio', null),
('HubSpot Blog', 'US', 'en', 'https://blog.hubspot.com/marketing', 'https://blog.hubspot.com/marketing/rss.xml', null, null, array['marketing'], 'medio', null),
('Marketing Directo', 'ES', 'es', 'https://www.marketingdirecto.com', 'https://www.marketingdirecto.com/feed', 'mkdirecto', null, array['marketing'], 'medio', null),
('PuroMarketing', 'ES', 'es', 'https://www.puromarketing.com', null, 'puromarketing', null, array['marketing'], 'medio', null),
('Merca2.0', 'MX', 'es', 'https://www.merca20.com', 'https://www.merca20.com/feed/', 'merca20', null, array['marketing'], 'medio', null),
('Meio & Mensagem', 'BR', 'pt', 'https://www.meioemensagem.com.br', 'https://www.meioemensagem.com.br/feed', 'meioemensagem', null, array['marketing'], 'medio', null),
('Nieman Lab', 'US', 'en', 'https://www.niemanlab.org', 'https://www.niemanlab.org/feed/', null, null, array['comunicacion'], 'medio', null),
('Press Gazette', 'GB', 'en', 'https://pressgazette.co.uk', 'https://pressgazette.co.uk/feed/', 'pressgazette', null, array['comunicacion'], 'medio', null),
('Reuters Institute', 'GB', 'en', 'https://reutersinstitute.politics.ox.ac.uk', 'https://reutersinstitute.politics.ox.ac.uk/rss.xml', 'risj_oxford', null, array['comunicacion'], 'medio', null),
('Poynter', 'US', 'en', 'https://www.poynter.org', 'https://www.poynter.org/feed/', 'Poynter', null, array['comunicacion'], 'medio', null),
('Columbia Journalism Review', 'US', 'en', 'https://www.cjr.org', 'https://www.cjr.org/feed', 'CJR', null, array['comunicacion'], 'medio', null),
('PR Daily', 'US', 'en', 'https://www.prdaily.com', 'https://www.prdaily.com/feed/', null, null, array['comunicacion'], 'medio', null),
('PRWeek', 'US', 'en', 'https://www.prweek.com', null, 'prweekus', null, array['comunicacion'], 'medio', null),
('Laboratorio de Periodismo', 'ES', 'es', 'https://laboratoriodeperiodismo.org', 'https://laboratoriodeperiodismo.org/feed/', null, null, array['comunicacion'], 'medio', null),
('PR Noticias', 'ES', 'es', 'https://prnoticias.com', 'https://prnoticias.com/feed/', 'prnoticias', null, array['comunicacion'], 'medio', null),
('LatAm Journalism Review', 'US', 'es', 'https://latamjournalismreview.org/es/', 'https://latamjournalismreview.org/es/feed/', null, null, array['comunicacion'], 'medio', null),
('Fundación Gabo', 'CO', 'es', 'https://fundaciongabo.org', 'https://fundaciongabo.org/es/rss.xml', 'FundacionGabo', null, array['comunicacion'], 'medio', null),
('Seth Godin', 'US', 'en', 'https://seths.blog', 'https://seths.blog/feed/', null, 'sethgodin.bsky.social', array['marketing'], 'referente', 'Autor y blogger, This is Marketing'),
('Scott Galloway', 'US', 'en', 'https://www.profgalloway.com', null, null, 'profgalloway.com', array['marketing'], 'referente', 'Profesor de NYU Stern, No Mercy / No Malice'),
('Rand Fishkin', 'US', 'en', 'https://sparktoro.com/blog', null, 'randfish', null, array['marketing'], 'referente', 'Fundador de SparkToro, audiencias y SEO'),
('Neil Patel', 'US', 'en', 'https://neilpatel.com/blog', 'https://neilpatel.com/blog/feed/', 'neilpatel', null, array['marketing'], 'referente', 'Marketing digital y SEO'),
('Gary Vaynerchuk', 'US', 'en', 'https://x.com/garyvee', null, 'garyvee', 'garyvee.com', array['marketing'], 'referente', 'VaynerMedia, redes y marca personal'),
('Kevin Indig', 'US', 'en', 'https://www.growth-memo.com', 'https://www.growth-memo.com/feed', 'Kevin_Indig', null, array['marketing'], 'referente', 'Growth y SEO, escribe Growth Memo'),
('Vilma Núñez', 'ES', 'es', 'https://vilmanunez.com', 'https://vilmanunez.com/feed/', null, null, array['marketing'], 'referente', 'Estratega de marketing digital'),
('Juan Merodio', 'ES', 'es', 'https://x.com/juanmerodio', null, 'juanmerodio', null, array['marketing'], 'referente', 'Marketing digital y ventas'),
('Andy Stalman', 'AR', 'es', 'https://x.com/AndyStalman', null, 'AndyStalman', null, array['marketing'], 'referente', 'Branding, autor de Brand Off-On'),
('Emily Bell', 'GB', 'en', 'https://x.com/emilybell', null, 'emilybell', 'emilybell.bsky.social', array['comunicacion'], 'referente', 'Tow Center (Columbia), medios y tecnología'),
('Margaret Sullivan', 'US', 'en', 'https://margaretsullivan.substack.com', 'https://margaretsullivan.substack.com/feed', null, 'sulliview.bsky.social', array['comunicacion'], 'referente', 'Columnista de medios, American Crisis'),
('Joshua Benton', 'US', 'en', 'https://x.com/jbenton', null, 'jbenton', 'joshuabenton.com', array['comunicacion'], 'referente', 'Fundador de Nieman Lab'),
('Brian Stelter', 'US', 'en', 'https://x.com/brianstelter', null, 'brianstelter', 'brianstelter.bsky.social', array['comunicacion'], 'referente', 'CNN, Reliable Sources'),
('Jeff Jarvis', 'US', 'en', 'https://buzzmachine.com', 'https://buzzmachine.com/feed/', 'jeffjarvis', 'jeffjarvis.bsky.social', array['comunicacion'], 'referente', 'Periodismo y tecnología, BuzzMachine'),
('Ramón Salaverría', 'ES', 'es', 'https://x.com/rsalaverria', null, 'rsalaverria', null, array['comunicacion'], 'referente', 'Catedrático de periodismo (Universidad de Navarra)'),
('Antoni Gutiérrez-Rubí', 'ES', 'es', 'https://www.gutierrez-rubi.es', 'https://www.gutierrez-rubi.es/feed/', 'antonigr', 'antonigr.bsky.social', array['comunicacion'], 'referente', 'Asesor de comunicación política'),
('Carlos Scolari', 'AR', 'es', 'https://hipermediaciones.com', 'https://hipermediaciones.com/feed/', 'cscolari', 'cscolari.bsky.social', array['comunicacion'], 'referente', 'Ecología de los medios, Hipermediaciones'),
('Mario Riorda', 'AR', 'es', 'https://x.com/marioriorda', null, 'marioriorda', null, array['comunicacion'], 'referente', 'Comunicación política y de gobierno'),
('Natalia Aruguete', 'AR', 'es', 'https://x.com/nataliaaruguete', null, 'nataliaaruguete', null, array['comunicacion'], 'referente', 'Investigadora en comunicación y redes (CONICET)')
) as m (medio, pais, idioma, sitio, rss, x, bluesky, temas, tipo, descripcion)
on conflict (owner_id, medio) do nothing;
