-- Referentes de cada tema para Canillita (migración noticias_referentes_inicial), verificados el 2026-10-01:
-- solo cuentas con posts propios del último mes (X vía FxTwitter, Bluesky por su API pública) o blog/newsletter
-- con notas de las últimas semanas. Todo lo que publican entra en su tema, sin filtrar por palabras.
insert into public.noticias_medios (owner_id, medio, pais, idioma, sitio, rss, x, bluesky, temas, tipo, descripcion)
select (select owner_id from public.trabajadores order by id limit 1), m.* from (values
('Andrej Karpathy', 'US', 'en', 'https://karpathy.ai', null, 'karpathy', null, array['ia'], 'referente', 'Investigador, cofundador de OpenAI y ex director de IA de Tesla'),
('Ethan Mollick', 'US', 'en', 'https://www.oneusefulthing.org', 'https://www.oneusefulthing.org/feed', 'emollick', 'emollick.bsky.social', array['ia'], 'referente', 'Profesor de Wharton, escribe One Useful Thing'),
('Simon Willison', 'GB', 'en', 'https://simonwillison.net', 'https://simonwillison.net/atom/everything/', 'simonw', 'simonwillison.net', array['ia'], 'referente', 'Desarrollador, el blog más leído sobre LLMs en la práctica'),
('Gary Marcus', 'US', 'en', 'https://garymarcus.substack.com', 'https://garymarcus.substack.com/feed', 'GaryMarcus', null, array['ia'], 'referente', 'Científico cognitivo, crítico de la IA generativa'),
('Demis Hassabis', 'GB', 'en', 'https://x.com/demishassabis', null, 'demishassabis', null, array['ia'], 'referente', 'CEO de Google DeepMind, Nobel de Química 2024'),
('Sam Altman', 'US', 'en', 'https://blog.samaltman.com', null, 'sama', null, array['ia'], 'referente', 'CEO de OpenAI'),
('Fei-Fei Li', 'US', 'en', 'https://x.com/drfeifei', null, 'drfeifei', null, array['ia'], 'referente', 'Profesora de Stanford, creadora de ImageNet'),
('Andrew Ng', 'US', 'en', 'https://www.deeplearning.ai/the-batch/', null, 'AndrewYNg', null, array['ia'], 'referente', 'Fundador de DeepLearning.AI, escribe The Batch'),
('Jack Clark', 'US', 'en', 'https://importai.substack.com', 'https://importai.substack.com/feed', 'jackclarkSF', null, array['ia'], 'referente', 'Cofundador de Anthropic, escribe Import AI'),
('Timnit Gebru', 'US', 'en', 'https://bsky.app/profile/timnitgebru.blacksky.app', null, null, 'timnitgebru.blacksky.app', array['ia'], 'referente', 'Fundadora de DAIR, ética de la IA'),
('Margaret Mitchell', 'US', 'en', 'https://bsky.app/profile/mmitchell.bsky.social', null, null, 'mmitchell.bsky.social', array['ia'], 'referente', 'Jefa de ética en Hugging Face'),
('Clement Delangue', 'FR', 'en', 'https://x.com/ClementDelangue', null, 'ClementDelangue', null, array['ia'], 'referente', 'CEO de Hugging Face'),
('Marietje Schaake', 'NL', 'en', 'https://bsky.app/profile/marietjeschaake.bsky.social', null, null, 'marietjeschaake.bsky.social', array['politica_ia'], 'referente', 'Ex eurodiputada, Stanford, autora de The Tech Coup'),
('Yoshua Bengio', 'CA', 'en', 'https://yoshuabengio.org', 'https://yoshuabengio.org/feed/', 'Yoshua_Bengio', 'yoshuabengio.bsky.social', array['politica_ia'], 'referente', 'Premio Turing, preside el informe internacional de seguridad de la IA'),
('Gabriela Ramos', 'MX', 'es', 'https://x.com/gabramosp', null, 'gabramosp', null, array['politica_ia'], 'referente', 'Ex subdirectora de UNESCO, recomendación global de ética de la IA'),
('Brando Benifei', 'IT', 'en', 'https://x.com/brandobenifei', null, 'brandobenifei', null, array['politica_ia'], 'referente', 'Eurodiputado, co-relator del AI Act'),
('Jeffrey Ding', 'US', 'en', 'https://chinai.substack.com', 'https://chinai.substack.com/feed', null, null, array['politica_ia'], 'referente', 'Profesor (GWU), escribe ChinAI sobre la IA en China'),
('Ian Bremmer', 'US', 'en', 'https://x.com/ianbremmer', null, 'ianbremmer', 'ianbremmer.com', array['politica_ia'], 'referente', 'Presidente de Eurasia Group, geopolítica y tecnología'),
('Lorena Jaume-Palasí', 'ES', 'es', 'https://bsky.app/profile/lopalasi.bsky.social', null, null, 'lopalasi.bsky.social', array['politica_ia'], 'referente', 'Fundadora de The Ethical Tech Society'),
('Michael Kratsios', 'US', 'en', 'https://x.com/mkratsios47', null, 'mkratsios47', null, array['politica_ia'], 'referente', 'Director de la oficina de ciencia y tecnología de la Casa Blanca'),
('Dean W. Ball', 'US', 'en', 'https://x.com/deanwball', null, 'deanwball', null, array['politica_ia'], 'referente', 'Analista de política de IA, escribe Hyperdimensional'),
('Miles Brundage', 'US', 'en', 'https://milesbrundage.substack.com', 'https://milesbrundage.substack.com/feed', 'Miles_Brundage', null, array['politica_ia'], 'referente', 'Investigador de política de IA, ex OpenAI'),
('Casey Newton', 'US', 'en', 'https://www.platformer.news', 'https://www.platformer.news/rss/', null, 'caseynewton.bsky.social', array['tecnologia'], 'referente', 'Escribe Platformer, coconduce Hard Fork'),
('Benedict Evans', 'GB', 'en', 'https://www.ben-evans.com', 'https://www.ben-evans.com/benedictevans?format=rss', null, null, array['tecnologia'], 'referente', 'Analista de tecnología, newsletter semanal'),
('Ben Thompson', 'TW', 'en', 'https://stratechery.com', 'https://stratechery.com/feed/', null, null, array['tecnologia'], 'referente', 'Escribe Stratechery, estrategia de la industria tech'),
('Marques Brownlee', 'US', 'en', 'https://x.com/MKBHD', null, 'MKBHD', null, array['tecnologia'], 'referente', 'MKBHD, reseñas de tecnología'),
('Mark Gurman', 'US', 'en', 'https://x.com/markgurman', null, 'markgurman', 'markgurman.bsky.social', array['tecnologia'], 'referente', 'Bloomberg, la fuente de todo lo de Apple'),
('John Gruber', 'US', 'en', 'https://daringfireball.net', 'https://daringfireball.net/feeds/main', 'gruber', 'gruber.foo', array['tecnologia'], 'referente', 'Daring Fireball'),
('Cory Doctorow', 'CA', 'en', 'https://pluralistic.net', 'https://pluralistic.net/feed/', 'doctorow', 'doctorow.pluralistic.net', array['tecnologia'], 'referente', 'Escritor y activista, Pluralistic'),
('Molly White', 'US', 'en', 'https://www.citationneeded.news', 'https://www.citationneeded.news/rss/', null, 'molly.wiki', array['tecnologia'], 'referente', 'Citation Needed, cripto y poder tech'),
('Kevin Roose', 'US', 'en', 'https://x.com/kevinroose', null, 'kevinroose', null, array['tecnologia'], 'referente', 'The New York Times, coconduce Hard Fork'),
('Enrique Dans', 'ES', 'es', 'https://www.enriquedans.com', 'https://www.enriquedans.com/feed', 'edans', null, array['tecnologia'], 'referente', 'Profesor de IE Business School, blog diario sobre tecnología'),
('Antonio Ortiz', 'ES', 'es', 'https://www.error500.net', 'https://www.error500.net/feed', 'antonello', null, array['tecnologia'], 'referente', 'Error500, coconduce Monos Estocásticos'),
('Ina Fried', 'US', 'en', 'https://x.com/inafried', null, 'inafried', 'inafried.bsky.social', array['tecnologia'], 'referente', 'Axios, newsletter Axios AI+'),
('Bruce Schneier', 'US', 'en', 'https://www.schneier.com', 'https://www.schneier.com/feed/atom/', null, null, array['ciberseguridad'], 'referente', 'Criptógrafo, Schneier on Security'),
('Troy Hunt', 'AU', 'en', 'https://www.troyhunt.com', 'https://www.troyhunt.com/rss/', 'troyhunt', 'troyhunt.com', array['ciberseguridad'], 'referente', 'Creador de Have I Been Pwned'),
('Mikko Hyppönen', 'FI', 'en', 'https://x.com/mikko', null, 'mikko', null, array['ciberseguridad'], 'referente', 'Investigador de malware'),
('Katie Moussouris', 'US', 'en', 'https://x.com/k8em0', null, 'k8em0', 'k8em0.bsky.social', array['ciberseguridad'], 'referente', 'Fundadora de Luta Security, bug bounties'),
('Kim Zetter', 'US', 'en', 'https://www.zetter-zeroday.com', 'https://www.zetter-zeroday.com/rss/', null, 'kimzetter.bsky.social', array['ciberseguridad'], 'referente', 'Periodista, Zero Day'),
('Lesley Carhart', 'US', 'en', 'https://bsky.app/profile/hacks4pancakes.com', null, null, 'hacks4pancakes.com', array['ciberseguridad'], 'referente', 'Respuesta a incidentes en infraestructura crítica'),
('Patrick Gray', 'AU', 'en', 'https://risky.biz', 'https://risky.biz/feeds/risky-business-news/', null, null, array['ciberseguridad'], 'referente', 'Risky Business, podcast y newsletter'),
('Chema Alonso', 'ES', 'es', 'https://www.elladodelmal.com', 'https://www.elladodelmal.com/feeds/posts/default', null, 'chemaalonso.com', array['ciberseguridad'], 'referente', 'Hacker, El lado del mal'),
('Cristian Borghello', 'AR', 'es', 'https://blog.segu-info.com.ar', 'https://blog.segu-info.com.ar/feeds/posts/default', 'seguinfo', null, array['ciberseguridad'], 'referente', 'Segu-Info, referente de seguridad en Argentina'),
('Jake Williams', 'US', 'en', 'https://x.com/MalwareJake', null, 'MalwareJake', 'malwarejake.bsky.social', array['ciberseguridad'], 'referente', 'Ex NSA, profesor de IANS'),
('Kevin Beaumont', 'GB', 'en', 'https://doublepulsar.com', null, null, 'doublepulsar.com', array['ciberseguridad'], 'referente', 'Investigador, DoublePulsar'),
('Aitana Bonmatí', 'ES', 'es', 'https://x.com/AitanaBonmati', null, 'AitanaBonmati', null, array['futbol_femenino'], 'referente', 'Barcelona, tres veces Balón de Oro'),
('Alex Morgan', 'US', 'en', 'https://x.com/alexmorgan13', null, 'alexmorgan13', null, array['futbol_femenino'], 'referente', 'Campeona del mundo, empresaria'),
('Suzanne Wrack', 'GB', 'en', 'https://x.com/SuzyWrack', null, 'SuzyWrack', null, array['futbol_femenino'], 'referente', 'The Guardian, fútbol femenino'),
('Jeff Kassouf', 'US', 'en', 'https://x.com/JeffKassouf', null, 'JeffKassouf', 'jeffkassouf.bsky.social', array['futbol_femenino'], 'referente', 'Fundador de The Equalizer'),
('Meg Linehan', 'US', 'en', 'https://bsky.app/profile/meglinehan.com', null, null, 'meglinehan.com', array['futbol_femenino'], 'referente', 'The Athletic, NWSL y selección de EE. UU.'),
('Asif Burhan', 'GB', 'en', 'https://x.com/AsifBurhan', null, 'AsifBurhan', null, array['futbol_femenino'], 'referente', 'Periodista especializado en fútbol femenino europeo'),
('Dibradoras', 'BR', 'pt', 'https://x.com/dibradoras', null, 'dibradoras', null, array['futbol_femenino'], 'referente', 'Colectivo de periodistas de deporte femenino de Brasil'),
('NWSL', 'US', 'en', 'https://x.com/NWSL', null, 'NWSL', null, array['futbol_femenino'], 'referente', 'Liga profesional de EE. UU. (cuenta oficial)'),
('Barclays WSL', 'GB', 'en', 'https://x.com/BarclaysWSL', null, 'BarclaysWSL', null, array['futbol_femenino'], 'referente', 'Liga inglesa (cuenta oficial)'),
('UEFA Women’s Champions League', 'EU', 'en', 'https://x.com/UWCL', null, 'UWCL', null, array['futbol_femenino'], 'referente', 'Champions femenina (cuenta oficial)'),
('FIFA Women’s World Cup', 'CH', 'en', 'https://x.com/FIFAWWC', null, 'FIFAWWC', null, array['futbol_femenino'], 'referente', 'Mundial femenino (cuenta oficial)'),
('Lionesses', 'GB', 'en', 'https://x.com/Lionesses', null, 'Lionesses', null, array['futbol_femenino'], 'referente', 'Selección de Inglaterra (cuenta oficial)'),
('USWNT', 'US', 'en', 'https://x.com/uswnt', null, 'uswnt', null, array['futbol_femenino'], 'referente', 'Selección de EE. UU. (cuenta oficial)'),
('Nate Silver', 'US', 'en', 'https://www.natesilver.net', 'https://www.natesilver.net/feed', 'NateSilver538', null, array['datos'], 'referente', 'Silver Bulletin, fundador de FiveThirtyEight'),
('John Burn-Murdoch', 'GB', 'en', 'https://bsky.app/profile/jburnmurdoch.ft.com', null, null, 'jburnmurdoch.ft.com', array['datos'], 'referente', 'Periodista de datos jefe del Financial Times'),
('Max Roser', 'GB', 'en', 'https://x.com/MaxCRoser', null, 'MaxCRoser', null, array['datos'], 'referente', 'Fundador de Our World in Data'),
('Alberto Cairo', 'US', 'en', 'https://www.thefunctionalart.com', null, null, 'albertocairo.com', array['datos'], 'referente', 'Visualización de datos, Universidad de Miami'),
('Hadley Wickham', 'NZ', 'en', 'https://bsky.app/profile/hadley.nz', null, null, 'hadley.nz', array['datos'], 'referente', 'Jefe científico de Posit, creador del tidyverse'),
('DJ Patil', 'US', 'en', 'https://x.com/dpatil', null, 'dpatil', null, array['datos'], 'referente', 'Primer Chief Data Scientist de EE. UU.'),
('Hilary Mason', 'US', 'en', 'https://bsky.app/profile/hilarymason.com', null, null, 'hilarymason.com', array['datos'], 'referente', 'Científica de datos, fundadora de Fast Forward Labs'),
('Kirk Borne', 'US', 'en', 'https://x.com/KirkDBorne', null, 'KirkDBorne', null, array['datos'], 'referente', 'Astrofísico y divulgador de ciencia de datos'),
('Cole Nussbaumer Knaflic', 'US', 'en', 'https://www.storytellingwithdata.com', 'https://www.storytellingwithdata.com/blog?format=rss', null, null, array['datos'], 'referente', 'Storytelling with Data'),
('Kiko Llaneras', 'ES', 'es', 'https://x.com/kikollan', null, 'kikollan', null, array['datos'], 'referente', 'Periodista de datos de El País'),
('Florencia Coelho', 'AR', 'es', 'https://x.com/fcoel', null, 'fcoel', null, array['datos'], 'referente', 'Periodismo de datos en La Nación'),
('Andy Kirk', 'GB', 'en', 'https://visualisingdata.com', null, null, 'visualisingdata.com', array['datos'], 'referente', 'Visualising Data')
) as m (medio, pais, idioma, sitio, rss, x, bluesky, temas, tipo, descripcion)
on conflict (owner_id, medio) do nothing;
