-- Lista inicial de medios de Canillita (migración noticias_medios_inicial), verificada el 2026-10-01:
-- web = feed con notas de los últimos 45 días (las notas viejas igual se descartan al leer); x = cuenta con posts de las últimas 3 semanas vía FxTwitter;
-- newsletter = link de suscripción encontrado en la portada. Se edita desde la base, no desde el código.
insert into public.noticias_medios (owner_id, medio, pais, idioma, sitio, rss, x, newsletter, temas)
select (select owner_id from public.trabajadores order by id limit 1), m.* from (values
('La Nación', 'AR', 'es', 'https://www.lanacion.com.ar', 'https://www.lanacion.com.ar/arc/outboundfeeds/rss/?outputType=xml', 'LANACION', 'https://newsletter.lanacion.com.ar/', '{}'::text[]),
('Clarín', 'AR', 'es', 'https://www.clarin.com', 'https://www.clarin.com/rss/tecnologia/', 'clarincom', 'https://www.clarin.com/newsletters', '{}'::text[]),
('Infobae', 'AR', 'es', 'https://www.infobae.com', 'https://www.infobae.com/arc/outboundfeeds/rss/', null, null, '{}'::text[]),
('Página/12', 'AR', 'es', 'https://www.pagina12.com.ar', null, 'pagina12', null, '{}'::text[]),
('Olé', 'AR', 'es', 'https://www.ole.com.ar', 'https://www.ole.com.ar/rss/futbol-femenino/', null, null, '{}'::text[]),
('iProfesional', 'AR', 'es', 'https://www.iprofesional.com', 'https://www.iprofesional.com/rss/tecnologia', 'iprofesional', null, '{}'::text[]),
('Chequeado', 'AR', 'es', 'https://chequeado.com', 'https://chequeado.com/feed/', null, 'https://chequeado.com/newsletters/', '{}'::text[]),
('El País Uruguay', 'UY', 'es', 'https://www.elpais.com.uy', 'https://www.elpais.com.uy/rss/', 'elpaisuy', 'https://web.elpais.com.uy/newsletters/', '{}'::text[]),
('La Tercera', 'CL', 'es', 'https://www.latercera.com', 'https://www.latercera.com/arc/outboundfeeds/rss/?outputType=xml', 'latercera', 'https://www.latercera.com/newsletters/', '{}'::text[]),
('BioBioChile', 'CL', 'es', 'https://www.biobiochile.cl', 'https://feeds.feedburner.com/radiobiobio/NNeJ', 'biobio', 'https://www.biobiochile.cl/newsletter', '{}'::text[]),
('ABC Color', 'PY', 'es', 'https://www.abc.com.py', 'https://www.abc.com.py/arc/outboundfeeds/rss/?outputType=xml', null, 'https://www.abc.com.py/newsletters/', '{}'::text[]),
('El Deber', 'BO', 'es', 'https://eldeber.com.bo', 'https://eldeber.com.bo/rss/feed.html', 'grupoeldeber', null, '{}'::text[]),
('Folha de S.Paulo', 'BR', 'pt', 'https://www.folha.uol.com.br', 'https://feeds.folha.uol.com.br/tec/rss091.xml', 'folha', 'https://minhafolha.folha.uol.com.br/newsletters', '{}'::text[]),
('g1', 'BR', 'pt', 'https://g1.globo.com', 'https://g1.globo.com/rss/g1/tecnologia/', 'g1', null, '{}'::text[]),
('ge (Globo Esporte)', 'BR', 'pt', 'https://ge.globo.com', 'https://ge.globo.com/rss/ge/futebol/futebol-feminino/', null, null, '{}'::text[]),
('Estadão', 'BR', 'pt', 'https://www.estadao.com.br', null, 'Estadao', 'https://meu.estadao.com.br/newsletter', '{}'::text[]),
('Tecnoblog', 'BR', 'pt', 'https://tecnoblog.net', 'https://tecnoblog.net/feed/', 'tecnoblog', null, '{}'::text[]),
('El Universal', 'MX', 'es', 'https://www.eluniversal.com.mx', 'https://www.eluniversal.com.mx/arc/outboundfeeds/rss/?outputType=xml', 'El_Universal_Mx', 'https://www.eluniversal.com.mx/newsletters/', '{}'::text[]),
('Expansión', 'MX', 'es', 'https://expansion.mx', 'https://expansion.mx/rss/tecnologia', null, null, '{}'::text[]),
('Milenio', 'MX', 'es', 'https://www.milenio.com', null, 'Milenio', 'https://www.milenio.com/suscripciones/newsletter', '{}'::text[]),
('La Nación CR', 'CR', 'es', 'https://www.nacion.com', 'https://www.nacion.com/arc/outboundfeeds/rss/?outputType=xml', 'nacion', 'https://www.nacion.com/boletines/', '{}'::text[]),
('Prensa Libre', 'GT', 'es', 'https://www.prensalibre.com', 'https://www.prensalibre.com/feed/', 'prensa_libre', 'https://www.prensalibre.com/boletines/', '{}'::text[]),
('El Nuevo Día', 'PR', 'es', 'https://www.elnuevodia.com', 'https://www.elnuevodia.com/arc/outboundfeeds/rss/?outputType=xml', 'ElNuevoDia', 'https://www.elnuevodia.com/newsletters', '{}'::text[]),
('La Prensa Panamá', 'PA', 'es', 'https://www.prensa.com', 'https://www.prensa.com/arc/outboundfeeds/rss/?outputType=xml', 'prensacom', null, '{}'::text[]),
('El Tiempo', 'CO', 'es', 'https://www.eltiempo.com', 'https://www.eltiempo.com/rss/tecnosfera.xml', 'ELTIEMPO', 'https://www.eltiempo.com/zona-usuario/boletines', '{}'::text[]),
('El Espectador', 'CO', 'es', 'https://www.elespectador.com', null, 'elespectador', null, '{}'::text[]),
('El Comercio', 'PE', 'es', 'https://elcomercio.pe', 'https://elcomercio.pe/arc/outboundfeeds/rss/?outputType=xml', 'elcomercio_peru', 'https://elcomercio.pe/newsletters', '{}'::text[]),
('RPP', 'PE', 'es', 'https://rpp.pe', 'https://rpp.pe/feed/tecnologia', 'RPPNoticias', 'https://newsletter.rpp.pe/catalogo', '{}'::text[]),
('Efecto Cocuyo', 'VE', 'es', 'https://efectococuyo.com', null, 'EfectoCocuyo', null, '{}'::text[]),
('El País', 'ES', 'es', 'https://elpais.com', 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/tecnologia/portada', null, 'https://plus.elpais.com/newsletters/lnp/1/346', '{}'::text[]),
('El Mundo', 'ES', 'es', 'https://www.elmundo.es', 'https://e00-elmundo.uecdn.es/elmundo/rss/portada.xml', 'elmundoes', 'https://www.elmundo.es/newsletters.html', '{}'::text[]),
('elDiario.es', 'ES', 'es', 'https://www.eldiario.es', 'https://www.eldiario.es/rss/tecnologia/', 'eldiarioes', 'https://usuarios.eldiario.es/boletines', '{}'::text[]),
('Xataka', 'ES', 'es', 'https://www.xataka.com', 'https://www.xataka.com/feedburner.xml', 'xataka', null, '{}'::text[]),
('Marca', 'ES', 'es', 'https://www.marca.com', 'https://e00-marca.uecdn.es/rss/futbol/futbol-femenino.xml', 'marca', null, array['futbol_femenino']),
('Relevo', 'ES', 'es', 'https://www.relevo.com', 'https://www.relevo.com/rss/', 'relevo', null, '{}'::text[]),
('Mundo Deportivo', 'ES', 'es', 'https://www.mundodeportivo.com', null, 'mundodeportivo', null, '{}'::text[]),
('RTVE', 'ES', 'es', 'https://www.rtve.es', null, 'rtve', null, '{}'::text[]),
('Europa Press', 'ES', 'es', 'https://www.europapress.es', 'https://www.europapress.es/rss/rss.aspx?ch=00564', null, 'https://www.europapress.es/newsletters/', '{}'::text[]),
('Agencia EFE', 'ES', 'es', 'https://efe.com', null, 'EFEnoticias', null, '{}'::text[]),
('The New York Times', 'US', 'en', 'https://www.nytimes.com', 'https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml', null, null, '{}'::text[]),
('The Washington Post', 'US', 'en', 'https://www.washingtonpost.com', 'https://feeds.washingtonpost.com/rss/business/technology', 'washingtonpost', 'https://washingtonpost.com/newsletters/', '{}'::text[]),
('The Verge', 'US', 'en', 'https://www.theverge.com', 'https://www.theverge.com/rss/index.xml', null, 'https://www.theverge.com/newsletters', '{}'::text[]),
('Wired', 'US', 'en', 'https://www.wired.com', 'https://www.wired.com/feed/rss', 'WIRED', 'https://www.wired.com/newsletter', '{}'::text[]),
('TechCrunch', 'US', 'en', 'https://techcrunch.com', 'https://techcrunch.com/feed/', 'TechCrunch', 'https://techcrunch.com/newsletters/', '{}'::text[]),
('Ars Technica', 'US', 'en', 'https://arstechnica.com', 'https://feeds.arstechnica.com/arstechnica/index', 'arstechnica', null, '{}'::text[]),
('MIT Technology Review', 'US', 'en', 'https://www.technologyreview.com', 'https://www.technologyreview.com/feed/', 'techreview', 'https://www.technologyreview.com/newsletter-preferences', '{}'::text[]),
('Politico', 'US', 'en', 'https://www.politico.com', 'https://rss.politico.com/technology.xml', 'politico', null, '{}'::text[]),
('Axios', 'US', 'en', 'https://www.axios.com', 'https://api.axios.com/feed/', 'axios', null, '{}'::text[]),
('CNN', 'US', 'en', 'https://edition.cnn.com', null, 'CNN', 'https://edition.cnn.com/newsletters', '{}'::text[]),
('CNN en Español', 'US', 'es', 'https://cnnespanol.cnn.com', null, 'CNNEE', 'https://www.cnn.com/newsletters', '{}'::text[]),
('NPR', 'US', 'en', 'https://www.npr.org', 'https://feeds.npr.org/1019/rss.xml', null, 'https://www.npr.org/newsletters/', '{}'::text[]),
('The Equalizer', 'US', 'en', 'https://equalizersoccer.com', 'https://equalizersoccer.com/feed/', null, null, array['futbol_femenino']),
('Just Women''s Sports', 'US', 'en', 'https://justwomenssports.com', 'https://justwomenssports.com/feed/', 'justwsports', 'https://justwomenssports.com/newsletter/', '{}'::text[]),
('VentureBeat', 'US', 'en', 'https://venturebeat.com', null, 'VentureBeat', null, '{}'::text[]),
('FlowingData', 'US', 'en', 'https://flowingdata.com', 'https://flowingdata.com/feed', null, null, array['datos']),
('KDnuggets', 'US', 'en', 'https://www.kdnuggets.com', 'https://www.kdnuggets.com/feed', 'kdnuggets', null, array['datos']),
('Rest of World', 'US', 'en', 'https://restofworld.org', 'https://restofworld.org/feed/latest/', 'restofworld', 'https://restofworld.org/newsletters/global/', array['tecnologia']),
('CBC', 'CA', 'en', 'https://www.cbc.ca', 'https://www.cbc.ca/webfeed/rss/rss-technology', null, 'https://subscriptions.cbc.ca/listmanagement', '{}'::text[]),
('The Globe and Mail', 'CA', 'en', 'https://www.theglobeandmail.com', 'https://www.theglobeandmail.com/arc/outboundfeeds/rss/category/business/technology/', 'globeandmail', 'https://www.theglobeandmail.com/newsletters/', '{}'::text[]),
('La Presse', 'CA', 'fr', 'https://www.lapresse.ca', 'https://www.lapresse.ca/affaires/techno/rss', 'LP_LaPresse', 'https://www.lapresse.ca/infolettres', '{}'::text[]),
('BBC News', 'GB', 'en', 'https://www.bbc.com', 'https://feeds.bbci.co.uk/news/technology/rss.xml', 'BBCNews', 'https://www.bbc.com/newsletters', '{}'::text[]),
('BBC Sport (fútbol femenino)', 'GB', 'en', 'https://www.bbc.com/sport/football/womens', 'https://feeds.bbci.co.uk/sport/football/womens/rss.xml', null, 'https://www.bbc.co.uk/bbcnewsletter', array['futbol_femenino']),
('BBC Mundo', 'GB', 'es', 'https://www.bbc.com/mundo', 'https://feeds.bbci.co.uk/mundo/rss.xml', 'bbcmundo', 'https://www.bbc.com/mundo/send/u184973209', '{}'::text[]),
('The Guardian (IA)', 'GB', 'en', 'https://www.theguardian.com', 'https://www.theguardian.com/technology/artificialintelligenceai/rss', null, 'https://www.theguardian.com/email-newsletters', array['ia']),
('The Guardian (tecnología)', 'GB', 'en', 'https://www.theguardian.com', 'https://www.theguardian.com/technology/rss', null, 'https://www.theguardian.com/email-newsletters', array['tecnologia']),
('The Guardian (fútbol femenino)', 'GB', 'en', 'https://www.theguardian.com', 'https://www.theguardian.com/football/womensfootball/rss', null, 'https://www.theguardian.com/email-newsletters', array['futbol_femenino']),
('Financial Times', 'GB', 'en', 'https://www.ft.com', 'https://www.ft.com/artificial-intelligence?format=rss', 'FT', null, '{}'::text[]),
('The Economist', 'GB', 'en', 'https://www.economist.com', 'https://www.economist.com/science-and-technology/rss.xml', 'TheEconomist', null, '{}'::text[]),
('The Register', 'GB', 'en', 'https://www.theregister.com', 'https://www.theregister.com/headlines.atom', 'TheRegister', 'https://account.theregister.com/login?r=https%3A%2F%2Faccount.theregister.com%2Fedit%2Fnewsletter%2F', '{}'::text[]),
('She Kicks', 'GB', 'en', 'https://shekicks.net', 'https://shekicks.net/feed/', null, null, array['futbol_femenino']),
('The Irish Times', 'IE', 'en', 'https://www.irishtimes.com', null, 'IrishTimes', 'https://www.irishtimes.com/newsletters/', '{}'::text[]),
('RTÉ', 'IE', 'en', 'https://www.rte.ie', 'https://www.rte.ie/feeds/rss/?index=/news/', null, 'https://www.rte.ie/id/profile/', '{}'::text[]),
('Le Monde', 'FR', 'fr', 'https://www.lemonde.fr', 'https://www.lemonde.fr/pixels/rss_full.xml', null, 'https://www.lemonde.fr/newsletters/', '{}'::text[]),
('Le Figaro', 'FR', 'fr', 'https://www.lefigaro.fr', 'https://www.lefigaro.fr/rss/figaro_secteur_high-tech.xml', 'Le_Figaro', 'https://moncompte.lefigaro.fr/decouvrez-les-newsletters', '{}'::text[]),
('Les Echos', 'FR', 'fr', 'https://www.lesechos.fr', 'https://services.lesechos.fr/rss/les-echos-tech-medias.xml', 'LesEchos', 'https://www.lesechos.fr/newsletters', '{}'::text[]),
('France 24 Español', 'FR', 'es', 'https://www.france24.com/es', 'https://www.france24.com/es/rss', 'France24_es', null, '{}'::text[]),
('L''Équipe', 'FR', 'fr', 'https://www.lequipe.fr', 'https://dwh.lequipe.fr/api/edito/rss?path=/Football/', null, null, '{}'::text[]),
('Footofeminin', 'FR', 'fr', 'https://www.footofeminin.fr', 'https://www.footofeminin.fr/xml/syndication.rss', 'footofeminin', 'https://www.footofeminin.fr/newsletter', array['futbol_femenino']),
('NZZ', 'CH', 'de', 'https://www.nzz.ch', 'https://www.nzz.ch/technologie.rss', 'NZZ', 'https://abo.nzz.ch/newsletter/', '{}'::text[]),
('Der Spiegel', 'DE', 'de', 'https://www.spiegel.de', 'https://www.spiegel.de/netzwelt/index.rss', 'derspiegel', 'https://www.spiegel.de/newsletter', '{}'::text[]),
('heise online', 'DE', 'de', 'https://www.heise.de', 'https://www.heise.de/rss/heise-atom.xml', null, 'https://www.heise.de/newsletter/', '{}'::text[]),
('FAZ', 'DE', 'de', 'https://www.faz.net', 'https://www.faz.net/rss/aktuell/', 'FAZ_NET', 'https://nl.faz.net/', '{}'::text[]),
('Die Zeit', 'DE', 'de', 'https://www.zeit.de', 'https://newsfeed.zeit.de/digital/index', 'zeitonline', 'https://www.zeit.de/newsletter/index', '{}'::text[]),
('DW Español', 'DE', 'es', 'https://www.dw.com/es', 'https://rss.dw.com/rdf/rss-sp-all', 'dw_espanol', 'https://corporate.dw.com/es/suscripci%C3%B3n-a-los-boletines/a-15718285', '{}'::text[]),
('kicker', 'DE', 'de', 'https://www.kicker.de', 'https://newsfeed.kicker.de/news/fussball', null, null, '{}'::text[]),
('Der Standard', 'AT', 'de', 'https://www.derstandard.at', 'https://www.derstandard.at/rss/web', 'derStandardat', null, '{}'::text[]),
('NOS', 'NL', 'nl', 'https://nos.nl', 'https://feeds.nos.nl/nosnieuwstech', null, null, '{}'::text[]),
('Corriere della Sera', 'IT', 'it', 'https://www.corriere.it', null, 'Corriere', 'https://www.corriere.it/newsletter/', '{}'::text[]),
('la Repubblica', 'IT', 'it', 'https://www.repubblica.it', 'https://www.repubblica.it/rss/tecnologia/rss2.0.xml', 'repubblica', 'https://www.repubblica.it/newsletter/', '{}'::text[]),
('ANSA', 'IT', 'it', 'https://www.ansa.it', null, 'Agenzia_Ansa', 'https://www.ansa.it/sito/static/newsletter/', '{}'::text[]),
('Público', 'PT', 'pt', 'https://www.publico.pt', 'https://feeds.feedburner.com/PublicoRSS', 'Publico', null, '{}'::text[]),
('Observador', 'PT', 'pt', 'https://observador.pt', 'https://observador.pt/feed/', 'observadorpt', 'https://observador.pt/newsletters/', '{}'::text[]),
('SVT', 'SE', 'sv', 'https://www.svt.se', 'https://www.svt.se/nyheter/rss.xml', null, null, '{}'::text[]),
('NRK', 'NO', 'no', 'https://www.nrk.no', 'https://www.nrk.no/toppsaker.rss', null, null, '{}'::text[]),
('DR', 'DK', 'da', 'https://www.dr.dk', 'https://www.dr.dk/nyheder/service/feeds/allenyheder', null, null, '{}'::text[]),
('Yle', 'FI', 'fi', 'https://yle.fi', 'https://feeds.yle.fi/uutiset/v1/majorHeadlines/YLE_UUTISET.rss', 'yleuutiset', null, '{}'::text[]),
('TVN24', 'PL', 'pl', 'https://tvn24.pl', 'https://tvn24.pl/najnowsze.xml', 'tvn24', 'https://tvn24.pl/plus/newslettery', '{}'::text[]),
('Kyiv Independent', 'UA', 'en', 'https://kyivindependent.com', 'https://kyivindependent.com/news-archive/rss/', 'KyivIndependent', 'https://kyivindependent.com/newsletters/', '{}'::text[]),
('TASS', 'RU', 'en', 'https://tass.com', 'https://tass.com/rss/v2.xml', 'tassagency_en', null, '{}'::text[]),
('Meduza', 'RU', 'en', 'https://meduza.io/en', 'https://meduza.io/rss/en/all', 'meduza_en', 'https://meduza.io/en/pages/newsletter', '{}'::text[]),
('Euronews', 'EU', 'en', 'https://www.euronews.com', 'https://www.euronews.com/rss', 'euronews', 'https://www.euronews.com/newsletters', '{}'::text[]),
('Politico Europe', 'EU', 'en', 'https://www.politico.eu', 'https://www.politico.eu/section/technology/feed/', 'POLITICOEurope', 'https://www.politico.eu/newsletters/', '{}'::text[]),
('Al Jazeera', 'QA', 'en', 'https://www.aljazeera.com', 'https://www.aljazeera.com/xml/rss/all.xml', 'AJEnglish', 'https://www.aljazeera.com/newsletters', '{}'::text[]),
('Times of Israel', 'IL', 'en', 'https://www.timesofisrael.com', 'https://www.timesofisrael.com/feed/', null, null, '{}'::text[]),
('The National', 'AE', 'en', 'https://www.thenationalnews.com', 'https://www.thenationalnews.com/arc/outboundfeeds/rss/?outputType=xml', 'TheNationalNews', 'https://www.thenationalnews.com/profile/?tab=newsletters', '{}'::text[]),
('Arab News', 'SA', 'en', 'https://www.arabnews.com', 'https://www.arabnews.com/rss.xml', null, null, '{}'::text[]),
('Daily Sabah', 'TR', 'en', 'https://www.dailysabah.com', 'https://www.dailysabah.com/rss/business/tech', 'DailySabah', null, '{}'::text[]),
('Ahram Online', 'EG', 'en', 'https://english.ahram.org.eg', null, 'ahramonline', null, '{}'::text[]),
('Hespress', 'MA', 'en', 'https://en.hespress.com', 'https://en.hespress.com/feed', null, null, '{}'::text[]),
('TechCentral', 'ZA', 'en', 'https://techcentral.co.za', 'https://techcentral.co.za/feed/', 'techcentral', null, '{}'::text[]),
('Premium Times', 'NG', 'en', 'https://www.premiumtimesng.com', 'https://www.premiumtimesng.com/feed', 'PremiumTimesng', null, '{}'::text[]),
('TechCabal', 'NG', 'en', 'https://techcabal.com', 'https://techcabal.com/feed/', 'techcabal', 'https://techcabal.com/category/newsletters/', array['tecnologia']),
('Nation', 'KE', 'en', 'https://nation.africa', 'https://nation.africa/kenya/rss.xml', 'NationAfrica', null, '{}'::text[]),
('The Hindu', 'IN', 'en', 'https://www.thehindu.com', 'https://www.thehindu.com/sci-tech/technology/feeder/default.rss', 'the_hindu', 'https://www.thehindu.com/newsletter-subscription/', '{}'::text[]),
('Times of India', 'IN', 'en', 'https://timesofindia.indiatimes.com', null, 'timesofindia', 'https://timesofindia.indiatimes.com/newsletterhome.cms', '{}'::text[]),
('The Indian Express', 'IN', 'en', 'https://indianexpress.com', 'https://indianexpress.com/section/technology/feed/', 'IndianExpress', 'https://indianexpress.com/newsletters/', '{}'::text[]),
('Mint', 'IN', 'en', 'https://www.livemint.com', 'https://www.livemint.com/rss/technology', 'livemint', null, '{}'::text[]),
('MediaNama', 'IN', 'en', 'https://www.medianama.com', 'https://www.medianama.com/feed/', 'medianama', 'https://www.medianama.com/daily-newsletter/', array['tecnologia']),
('Dawn', 'PK', 'en', 'https://www.dawn.com', 'https://www.dawn.com/feeds/home', 'dawn_com', null, '{}'::text[]),
('The Daily Star', 'BD', 'en', 'https://www.thedailystar.net', null, 'dailystarnews', null, '{}'::text[]),
('South China Morning Post', 'CN', 'en', 'https://www.scmp.com', 'https://www.scmp.com/rss/36/feed', 'SCMPNews', null, '{}'::text[]),
('Global Times', 'CN', 'en', 'https://www.globaltimes.cn', 'https://www.globaltimes.cn/rss/outbrain.xml', 'globaltimesnews', null, '{}'::text[]),
('China Daily', 'CN', 'en', 'https://www.chinadaily.com.cn', null, 'ChinaDaily', 'https://www.chinadaily.com.cn/e/newsletter', '{}'::text[]),
('Sixth Tone', 'CN', 'en', 'https://www.sixthtone.com', 'https://www.sixthtone.com/rss', 'SixthTone', null, '{}'::text[]),
('The Japan Times', 'JP', 'en', 'https://www.japantimes.co.jp', 'https://www.japantimes.co.jp/feed/', 'japantimes', null, '{}'::text[]),
('Nikkei Asia', 'JP', 'en', 'https://asia.nikkei.com', 'https://asia.nikkei.com/rss/feed/nar', 'NikkeiAsia', 'https://asia.nikkei.com/member/register/newsletter', '{}'::text[]),
('Yonhap', 'KR', 'en', 'https://en.yna.co.kr', 'https://en.yna.co.kr/RSS/news.xml', 'YonhapNews', null, '{}'::text[]),
('The Korea Herald', 'KR', 'en', 'https://www.koreaherald.com', 'https://www.koreaherald.com/rss/newsAll', 'TheKoreaHerald', 'https://www.koreaherald.com/mypage', '{}'::text[]),
('Taipei Times', 'TW', 'en', 'https://www.taipeitimes.com', 'https://www.taipeitimes.com/xml/index.rss', null, null, '{}'::text[]),
('Focus Taiwan', 'TW', 'en', 'https://focustaiwan.tw', null, 'Focus_Taiwan', null, '{}'::text[]),
('The Straits Times', 'SG', 'en', 'https://www.straitstimes.com', null, 'straits_times', 'https://www.straitstimes.com/newsletter-signup', '{}'::text[]),
('CNA', 'SG', 'en', 'https://www.channelnewsasia.com', 'https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml', null, 'https://www.channelnewsasia.com/newsletters', '{}'::text[]),
('Rappler', 'PH', 'en', 'https://www.rappler.com', 'https://www.rappler.com/feed/', 'rapplerdotcom', 'https://www.rappler.com/newsletters', '{}'::text[]),
('VnExpress International', 'VN', 'en', 'https://e.vnexpress.net', 'https://e.vnexpress.net/rss/news.rss', null, null, '{}'::text[]),
('Bangkok Post', 'TH', 'en', 'https://www.bangkokpost.com', null, 'BangkokPostNews', 'https://www.bangkokpost.com/newsletter', '{}'::text[]),
('The Jakarta Post', 'ID', 'en', 'https://www.thejakartapost.com', null, 'jakpost', 'https://www.thejakartapost.com/newsletter', '{}'::text[]),
('The Star', 'MY', 'en', 'https://www.thestar.com.my', null, 'staronline', null, '{}'::text[]),
('ABC News', 'AU', 'en', 'https://www.abc.net.au', 'https://www.abc.net.au/news/feed/2942460/rss.xml', null, 'https://www.abc.net.au/news/subscribe', '{}'::text[]),
('The Sydney Morning Herald', 'AU', 'en', 'https://www.smh.com.au', 'https://www.smh.com.au/rss/technology.xml', 'smh', 'https://www.smh.com.au/newsletters', '{}'::text[]),
('RNZ', 'NZ', 'en', 'https://www.rnz.co.nz', 'https://www.rnz.co.nz/rss/national.xml', null, 'https://www.rnz.co.nz/newsletters', '{}'::text[]),
('NZ Herald', 'NZ', 'en', 'https://www.nzherald.co.nz', 'https://www.nzherald.co.nz/arc/outboundfeeds/rss/section/technology/?outputType=xml', null, 'https://www.nzherald.co.nz/my-account/profile/newsletters/', '{}'::text[]),
('The Decoder', 'DE', 'en', 'https://the-decoder.com', 'https://the-decoder.com/feed/', null, null, array['ia']),
('Our World in Data', 'GB', 'en', 'https://ourworldindata.org', 'https://ourworldindata.org/atom.xml', null, 'https://ourworldindata.org/subscribe', array['datos']),
('BleepingComputer', 'US', 'en', 'https://www.bleepingcomputer.com', 'https://www.bleepingcomputer.com/feed/', null, null, array['ciberseguridad']),
('The Record', 'US', 'en', 'https://therecord.media', 'https://therecord.media/feed', null, 'https://therecord.media/subscribe', array['ciberseguridad']),
('Krebs on Security', 'US', 'en', 'https://krebsonsecurity.com', 'https://krebsonsecurity.com/feed/', null, null, array['ciberseguridad']),
('Dark Reading', 'US', 'en', 'https://www.darkreading.com', 'https://www.darkreading.com/rss.xml', 'DarkReading', null, array['ciberseguridad']),
('SecurityWeek', 'US', 'en', 'https://www.securityweek.com', 'https://www.securityweek.com/feed/', null, 'https://www.securityweek.com/subscribe/', array['ciberseguridad']),
('The Hacker News', 'IN', 'en', 'https://thehackernews.com', 'https://feeds.feedburner.com/TheHackersNews', 'TheHackersNews', null, array['ciberseguridad']),
('WeLiveSecurity (ESET)', 'SK', 'es', 'https://www.welivesecurity.com/es/', 'https://www.welivesecurity.com/es/rss/feed/', 'ESETLA', null, array['ciberseguridad']),
('Una al Día (Hispasec)', 'ES', 'es', 'https://unaaldia.hispasec.com', 'https://unaaldia.hispasec.com/feed', null, null, array['ciberseguridad']),
('INCIBE', 'ES', 'es', 'https://www.incibe.es', 'https://www.incibe.es/incibe-cert/alerta-temprana/avisos/feed', 'INCIBE', null, array['ciberseguridad'])
) as m (medio, pais, idioma, sitio, rss, x, newsletter, temas)
on conflict (owner_id, medio) do nothing;
